name: Remote Backup Workflow

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE }}
        
      - name: Add SSH keyscan
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
         
      - name: Set up date variables
        id: date
        run: |
          echo "BACKUP_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "BACKUP_DIR=test-$BACKUP_DATE" >> $GITHUB_ENV
          echo "OLD_BACKUP_DATE=$(date -d 'yesterday' +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "OLD_BACKUP_DIR=test-$OLD_BACKUP_DATE" >> $GITHUB_ENV

      - name: Create backup directory on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "mkdir -p /opt/testing/backup/${{ env.BACKUP_DIR }}"

      - name: Perform backup on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "rsync -av /var/www/test/ /opt/testing/backup/${{ env.BACKUP_DIR }}/"

      - name: Remove previous day's backup on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "if [ -d /opt/testing/backup/${{ env.OLD_BACKUP_DIR }} ]; then rm -rf /opt/testing/backup/${{ env.OLD_BACKUP_DIR }}; fi"
